### ISSUE TITLE
Rules for contributing CSS

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/mezzanine#971]
How do you feel about creating some rules for contributing CSS? Everybody has it's own style, but I'd like to propose these:
1. Selectors, rules, hex colors (everything) is lowercase.
2. Use dashes to name classes and ids consisting of multiple words (no CamelCase, no under_scores)
3. Indent with four spaces.
4. One selector per line.
5. One rule per line.
6. Rules ordered alphabetically.
7. Add a space after each colon.
8. All rules end in semicolon, no spaces between the rule and the semicolon.
9. Opening bracket in the same line as selector, closing bracket on its own line.
10. Separate sections with 38 char wide blocks of commented "=====" and ALL CAPS title.

The advantages: consistence, easier reading of CSS diffs, uniformity with external tools (this is how browser inspectors render stylesheets). I can contribute this to the docs (with examples) once we agree on it.

``` css
/* Foobar Styles */
#MyElement, .my_class {width:100px; font-size:12px; line-height:30px; color:#FADE12}

/*=====================================
            FOOBAR STYLES
=======================================*/
#my-element,
.my-class {
    color: #fade12;
    font-size: 12px;
    line-height: 30px;
    width: 100px;
}
```
